flags:
extra-package-dbs: []
packages:
- opentracing
- opentracing-cloudtrace
- opentracing-examples
- opentracing-http-client
- opentracing-jaeger
- opentracing-wai
- opentracing-zipkin
extra-deps:
- thrift-0.10.0
allow-newer: true
resolver: lts-9.6
