_include: !include '../share/package.yaml'

name: opentracing-zipkin-common

synopsis: Zipkin OpenTracing Backend Commons

description: >
    Commons for the @opentracing-zipkin-v1@ and @opentracing-zipkin-v2@ packages

<<: *common
<<: *version
<<: *options

library:
  exposed-modules:
    - OpenTracing.Zipkin.Types

  dependencies:
    - aeson
    - base
    - opentracing
    - text
