_include: !include '../share/package.yaml'

name: opentracing-wai

synopsis: Middleware adding OpenTracing tracing for WAI applications

<<: *common
<<: *version
<<: *options

library:
  exposed-modules:
    - Network.Wai.Middleware.OpenTracing

  dependencies:
    - base
    - lens
    - opentracing
    - text
    - wai
