_include: !include '../share/package.yaml'

name: opentracing-cloudtrace

synopsis: OpenTracing reporter for Google Cloudtrace (aka Stackdriver Trace)

<<: *common
<<: *version
<<: *options

library:
  exposed-modules:
    - OpenTracing.CloudTrace

  dependencies:
    - aeson
    - base
    - exceptions
    - gogol
    - gogol-cloudtrace
    - gogol-logging
    - http-client
    - lens
    - opentracing
    - text
    - time
    - unordered-containers
