_include: !include '../share/package.yaml'

name: opentracing-zipkin-v1

synopsis: Zipkin V1 backend for OpenTracing

<<: *common
<<: *version
<<: *options

library:
  source-dirs:
    - src
    - gen-src

  exposed-modules:
    - OpenTracing.Zipkin.V1
    - OpenTracing.Zipkin.V1.HttpReporter
    - OpenTracing.Zipkin.V1.Thrift

  other-modules:
    - ZipkinCore_Consts
    - ZipkinCore_Types

  dependencies:
    - base
    - bytestring
    - exceptions
    - hashable
    - http-client
    - http-types
    - iproute
    - lens
    - opentracing
    - opentracing-zipkin-common
    - QuickCheck
    - text
    - thrift
    - unordered-containers
    - vector
